import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./_components/Navbar/Navbar";
import { Exo } from "next/font/google";
import Footer from "./_components/Footer/Footer";

export const metadata: Metadata = {
  title: "FreshCart",
  description: "Generated by create next app",
};

const exo = Exo({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={exo.className}>
        <Navbar />
        <>{children}</>
        <Footer />
      </body>
    </html>
  );
}
